name: Publish Production Topology

on:
  push:
    branches:
      - main
    paths:
      - 'production/**'

permissions: read-all

jobs:
  publish_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload production topology to DO Spaces
        uses: shallwefootball/upload-s3-action@master
        with:
          aws_key_id: ${{ secrets.DO_SPACES_KEY }}
          aws_secret_access_key: ${{ secrets.DO_SPACES_SECRET }}
          aws_bucket: sprinter-signing-config
          source_dir: './production'
          destination_dir: 'production'
          endpoint: https://ams3.digitaloceanspaces.com
